export const refundRequests = [
  {
    id: "#REQ1021",
    customer: "سارا مهدوی",
    product: "هدفون بی‌سیم",
    reason: "خرابی محصول",
    date: "۱۲ فروردین ۱۴۰۳",
    status: "در انتظار",
    avatar: "/user.jpg",
  },
  {
    id: "#REQ1022",
    customer: "امین رضایی",
    product: "کیف چرمی",
    reason: "سایز اشتباه",
    date: "۰۸ فروردین ۱۴۰۳",
    status: "در انتظار",
    avatar: "/user.jpg",
  },
  {
    id: "#REQ1023",
    customer: "نرگس شریفی",
    product: "ساعت هوشمند",
    reason: "تأخیر در تحویل",
    date: "۰۵ فروردین ۱۴۰۳",
    status: "تایید شد",
    avatar: "/user.jpg",
  },
  {
    id: "#REQ1024",
    customer: "علی احمدی",
    product: "کتونی ورزشی",
    reason: "عدم تطابق رنگ",
    date: "۰۳ فروردین ۱۴۰۳",
    status: "رد شد",
    avatar: "/user.jpg",
  },
  {
    id: "#REQ1025",
    customer: "هدیه فراهانی",
    product: "لباس مجلسی",
    reason: "اندازه نامناسب",
    date: "۰۱ فروردین ۱۴۰۳",
    status: "در انتظار",
    avatar: "/user.jpg",
  },
  {
    id: "#REQ1026",
    customer: "محمد عابدی",
    product: "عینک آفتابی",
    reason: "شکسته شده",
    date: "۲۹ اسفند ۱۴۰۲",
    status: "تایید شد",
    avatar: "/user.jpg",
  },
  {
    id: "#REQ1027",
    customer: "لیلا شریعتی",
    product: "تبلت سامسونگ",
    reason: "مشکل فنی",
    date: "۲۷ اسفند ۱۴۰۲",
    status: "رد شد",
    avatar: "/user.jpg",
  },
  {
    id: "#REQ1028",
    customer: "مهدی حسینی",
    product: "بازی پلی‌استیشن",
    reason: "پلمپ نبود",
    date: "۲۵ اسفند ۱۴۰۲",
    status: "در انتظار",
    avatar: "/user.jpg",
  },
  {
    id: "#REQ1029",
    customer: "زهرا تاجیک",
    product: "لپ‌تاپ ASUS",
    reason: "باطری خراب",
    date: "۲۲ اسفند ۱۴۰۲",
    status: "تایید شد",
    avatar: "/user.jpg",
  },
  {
    id: "#REQ1030",
    customer: "مجتبی جلالی",
    product: "موبایل شیائومی",
    reason: "فعال‌سازی نشده",
    date: "۲۰ اسفند ۱۴۰۲",
    status: "در انتظار",
    avatar: "/user.jpg",
  },
];

export const refundProcessing = [
  {
    id: "#REF321",
    name: "رضا نادری",
    product: "دوربین دیجیتال",
    status: "در حال بررسی",
    date: "۱۴ فروردین ۱۴۰۳",
    avatar: "/user.jpg",
  },
  {
    id: "#REF322",
    name: "لیلا فتحی",
    product: "ساعت هوشمند",
    status: "تایید شده",
    date: "۱۶ فروردین ۱۴۰۳",
    avatar: "/user.jpg",
  },
  {
    id: "#REF323",
    name: "حمیدرضا ملک‌زاده",
    product: "کفش اسپرت",
    status: "رد شده",
    date: "۱۷ فروردین ۱۴۰۳",
    avatar: "/user.jpg",
  },
  {
    id: "#REF324",
    name: "مهسا کریمی",
    product: "گوشی موبایل",
    status: "در حال بررسی",
    date: "۱۸ فروردین ۱۴۰۳",
    avatar: "/user.jpg",
  },
  {
    id: "#REF325",
    name: "پوریا عباسی",
    product: "هدفون بلوتوثی",
    status: "تایید شده",
    date: "۱۹ فروردین ۱۴۰۳",
    avatar: "/user.jpg",
  },
  {
    id: "#REF326",
    name: "نازنین شریفی",
    product: "کیبورد مکانیکی",
    status: "در حال بررسی",
    date: "۲۰ فروردین ۱۴۰۳",
    avatar: "/user.jpg",
  },
  {
    id: "#REF327",
    name: "علیرضا احمدی",
    product: "ماوس بی‌سیم",
    status: "رد شده",
    date: "۲۱ فروردین ۱۴۰۳",
    avatar: "/user.jpg",
  },
  {
    id: "#REF328",
    name: "سحر سلیمانی",
    product: "کتونی ورزشی",
    status: "تایید شده",
    date: "۲۲ فروردین ۱۴۰۳",
    avatar: "/user.jpg",
  },
  {
    id: "#REF329",
    name: "مهدی کاظمی",
    product: "کاور لپ‌تاپ",
    status: "در حال بررسی",
    date: "۲۳ فروردین ۱۴۰۳",
    avatar: "/user.jpg",
  },
  {
    id: "#REF330",
    name: "هدیه امینی",
    product: "تبلت",
    status: "رد شده",
    date: "۲۴ فروردین ۱۴۰۳",
    avatar: "/user.jpg",
  },
];
