export const customers = [
  {
    id: 1,
    name: "محمد امینی",
    avatar: "/demo1.jpg",
    invoiceId: "#INV2540",
    status: "تکمیل‌شده",
    total: "$4,521",
    due: "$8,901",
    date: "07 ژانویه 2023",
    method: "Mastercard",
  },
  {
    id: 2,
    name: "زهرا رضایی",
    avatar: "/demo1.jpg",
    invoiceId: "#INV3924",
    status: "لغو شده",
    total: "$7,836",
    due: "$9,902",
    date: "03 دسامبر 2023",
    method: "Visa",
  },
  {
    id: 3,
    name: "علی کریمی",
    avatar: "/demo1.jpg",
    invoiceId: "#INV5032",
    status: "تکمیل‌شده",
    total: "$1,347",
    due: "$6,718",
    date: "28 سپتامبر 2023",
    method: "Paypal",
  },
  {
    id: 4,
    name: "نگار محمدی",
    avatar: "/demo1.jpg",
    invoiceId: "#INV1695",
    status: "در انتظار",
    total: "$9,457",
    due: "$3,928",
    date: "10 آگوست 2023",
    method: "Mastercard",
  },
  {
    id: 5,
    name: "سارا حسینی",
    avatar: "/demo1.jpg",
    invoiceId: "#INV3725",
    status: "تکمیل‌شده",
    total: "$3,672",
    due: "$2,500",
    date: "15 آوریل 2023",
    method: "Visa",
  },
  {
    id: 6,
    name: "امیر عباس",
    avatar: "/demo3.jpg",
    invoiceId: "#INV4869",
    status: "در انتظار",
    total: "$6,221",
    due: "$4,100",
    date: "12 مارس 2023",
    method: "Mastercard",
  },
  {
    id: 7,
    name: "کیانا تهرانی",
    avatar: "/demo4.jpg",
    invoiceId: "#INV5791",
    status: "لغو شده",
    total: "$2,490",
    due: "$1,100",
    date: "20 فوریه 2023",
    method: "Paypal",
  },
  {
    id: 8,
    name: "پیمان صالحی",
    avatar: "/demo5.jpg",
    invoiceId: "#INV6854",
    status: "تکمیل‌شده",
    total: "$5,823",
    due: "$7,560",
    date: "04 ژوئن 2023",
    method: "Visa",
  },
  {
    id: 9,
    name: "ندا قاسمی",
    avatar: "/demo6.jpg",
    invoiceId: "#INV7992",
    status: "در انتظار",
    total: "$4,021",
    due: "$1,560",
    date: "11 مه 2023",
    method: "Mastercard",
  },
  {
    id: 10,
    name: "سینا محمدی",
    avatar: "/demo7.jpg",
    invoiceId: "#INV8427",
    status: "لغو شده",
    total: "$6,050",
    due: "$2,380",
    date: "23 ژوئیه 2023",
    method: "Paypal",
  },
  {
    id: 11,
    name: "مریم احمدی",
    avatar: "/demo8.jpg",
    invoiceId: "#INV9341",
    status: "تکمیل‌شده",
    total: "$8,510",
    due: "$5,230",
    date: "17 فوریه 2023",
    method: "Visa",
  },
  {
    id: 12,
    name: "آرمان بهرامی",
    avatar: "/demo9.jpg",
    invoiceId: "#INV1023",
    status: "در انتظار",
    total: "$3,900",
    due: "$6,200",
    date: "02 مارس 2023",
    method: "Mastercard",
  },
  {
    id: 13,
    name: "مونا غلامی",
    avatar: "/demo10.jpg",
    invoiceId: "#INV1185",
    status: "تکمیل‌شده",
    total: "$7,140",
    due: "$8,450",
    date: "29 ژوئن 2023",
    method: "Paypal",
  },
];
