
export const purchaseData = [
  {
    id: "#INV2540",
    name: "مایکل ای. ماینر",
    items: "تی‌شرت، کیف پول",
    status: "دریافت شد",
    date: "۰۷ ژانویه ۲۰۲۳",
    total: "$۶۲۱",
    method: "مسترکارت",
    paymentStatus: "موفق",
  },
  {
    id: "#INV3924",
    name: "ترزا تی. بروز",
    items: "پیراهن طلایی، عینک آفتابی",
    status: "دریافت شد",
    date: "۰۳ دسامبر ۲۰۲۳",
    total: "$۵۰۲",
    method: "ویزا",
    paymentStatus: "لغو",
  },
  {
    id: "#INV1120",
    name: "علی حسینی",
    items: "کت، شلوار",
    status: "معلق",
    date: "۱۰ فوریه ۲۰۲۴",
    total: "$۴۳۲",
    method: "پرداخت نقدی",
    paymentStatus: "معلق",
  },
  {
    id: "#INV2201",
    name: "سارا مرادی",
    items: "شال، کیف دستی",
    status: "دریافت شد",
    date: "۱۵ مارس ۲۰۲۴",
    total: "$۳۵۰",
    method: "زرین‌پال",
    paymentStatus: "موفق",
  },
  {
    id: "#INV1325",
    name: "کامران رضایی",
    items: "کفش، جوراب",
    status: "در انتظار",
    date: "۲۸ مارس ۲۰۲۴",
    total: "$۲۸۵",
    method: "مسترکارت",
    paymentStatus: "لغو",
  },
  {
    id: "#INV6743",
    name: "نگار صادقی",
    items: "سویشرت، ساعت",
    status: "دریافت شد",
    date: "۰۲ آوریل ۲۰۲۴",
    total: "$۷۴۰",
    method: "ویزا",
    paymentStatus: "موفق",
  },
  {
    id: "#INV8802",
    name: "حسین نجفی",
    items: "کلاه، پیراهن",
    status: "معلق",
    date: "۱۲ آوریل ۲۰۲۴",
    total: "$۱۹۸",
    method: "پرداخت نقدی",
    paymentStatus: "معلق",
  },
  {
    id: "#INV4431",
    name: "فرزانه موسوی",
    items: "عطر، لباس زنانه",
    status: "دریافت شد",
    date: "۱۹ آوریل ۲۰۲۴",
    total: "$۶۷۰",
    method: "زرین‌پال",
    paymentStatus: "موفق",
  },
];
